import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Header, Footer } from "@/sections";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "WhiteCode",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextUIProvider>
					<Header />
					{children}
					<Footer />
				</NextUIProvider>
			</body>
		</html>
	);
}
